### ISSUE TITLE
Option to quit

### ISSUE THREAD

**Issue by stephenway** [ryanmaxwell/iArrived#1]
Playing around with your app was fun but when it came time to quit I had to open up activity monitor. Maybe add a right click menu with the option? Or add a quit button to the window?

**Comment by ryanmaxwell** [comment]
Sure, makes sense. Command-Q works for now

**Comment by ryanmaxwell** [comment]
I've added a quit button to the popover https://github.com/ryanmaxwell/iArrived/commit/1a53e5e34043323bd2ad089a20ca932e851e2da3
