### ISSUE TITLE
Support for Multi-band Routers

### ISSUE THREAD

**Issue by stephenway** [ryanmaxwell/iArrived#2]
Not sure if it's possible but I'm using an Apple Extreme with all my iDevices on 2.4ghz and Macs on 5ghz. I'm assuming this is why the app doesn't work for me.

**Comment by ryanmaxwell** [comment]
I'm not sure if that is the case - I have an airport extreme also and haven't noticed this. Are you sure you have enabled WiFi syncing in iTunes? What if you connect your mac temporarily to the 2.4ghz network?
